### ISSUE TITLE
Add per-branch support

### ISSUE THREAD

**Issue by emendoza2** [mist8kengas/helmsman#1]
Allow configuring webhooks to respond on events of just a branch (e.g. `push`). This can be done with the `ref` attribute. [See this StackOverflow question](https://stackoverflow.com/questions/46140233/github-webhooks-triggered-globally-instead-of-per-branch).

**Comment by mist8kengas** [comment]
Implemented in [03b916e](https://github.com/mist8kengas/helmsman/commit/03b916e3fd9b1a8669c8fe632cbf05eb2a0fd754)
